### PR TITLE
CI: Enable GitHub Merge Queue; also, skip the "full tests" on PR runs, but continue to run them on Merge Queue runs

### PR DESCRIPTION
**Pull request by DilumAluthge**
Includes:
- #22

### CODE REVIEW

**Comment by DilumAluthge** [comment]
This should be merged first, before any of the other PRs.

Once this PR has been merged, we can then use GitHub Merge Queue for the subsequent PRs.

**Review by ararslan — APPROVED** [review]
Awesome, I'm not even sure I knew this was a thing!

**Comment by ararslan** [comment]
Btw, we may want to consider not running the "Full test" CI check on every PR... it always takes >1 hour and I've seen it take ~2.5 hours before.

**Comment by DilumAluthge** [comment]
> Btw, we may want to consider not running the "Full test" CI check on every PR... it always takes >1 hour and I've seen it take ~2.5 hours before.

We could consider skipping "Full test" on the PR run, but then still run it on the merge queue job.

**Comment by DilumAluthge** [comment]
> > Btw, we may want to consider not running the "Full test" CI check on every PR... it always takes >1 hour and I've seen it take ~2.5 hours before.
> 
> We could consider skipping "Full test" on the PR run, but then still run it on the merge queue job.

Implemented in #22.

**Comment by DilumAluthge** [comment]
Ugh. I'll increase the timeout in the repo settings to something larger.

**Comment by DilumAluthge** [comment]
> Ugh. I'll increase the timeout in the repo settings to something larger.

I've increased the timeout (in the "Merge Queue" section of the branch protection settings) to `360` minutes.

**Comment by DilumAluthge** [comment]
Also:
1. I merged #22 into this PR.
2. I simplified two of the job names.

**Comment by DilumAluthge** [comment]
Why is this not merging?

**Comment by DilumAluthge** [comment]
Ah, I remember the issue now.

If we have a job that is run conditionally (in this case, the "full test" is run conditionally - we don't run it on PRs, but we do run it on the merge queue), then that job CANNOT use a matrix, because using a matrix will mess up the branch protection settings. Basically, the issue is that the name of the job is different in the two different cases, and that mismatch causes either (1) all PRs are blocked, or (2) PRs are fine, but then the merge queue hangs indefinitely.

The fix is to go to all the jobs that are run conditionally (in this case, just the "full test" job), and remove the matrix.

In contrast, if we have a job that is run unconditionally (in this case, the "package test" job is run all the time, unconditionally), then that job can use a matrix, without any problems.

**Pull request merged**
